### PR TITLE
Adds CTA grid and makes adjustment to background image and fonts. 

### PR DESCRIPTION
**Pull request by oilsinwater**
@Erioldoesdesign here's an update. I've added the CTA and added the right mono font (was using JetBrains Mono mistakenly instead of IBM Plex Mono). 

For the background graphic to solve for smaller screens the image just disappears when it starts to look weird, and the CTA columns just become one.

Solves #58 and #54 there's more to do, but it looks 90% there to me, but lmk.

### CODE REVIEW

**Comment by oilsinwater** [comment]
This deploy failed but not sure why...will check asap.

**Review by SaptakS — CHANGES_REQUESTED** [review]
Can we make the CTAs as an `<a>` tag instead of `<button>` ? Since clicking it navigates to a different page, it should semantically be a link and not a button. Also, with anchor tag, you can just add `href` and don't need the `onclick` event.

**Comment by oilsinwater** [comment]
Good points @SaptakS. 

the buttons are for navigation, I'll correct. 

And I'm nesting the media query for the CTA because my brain desperately wants to use sass for some reason. I'll fix asap.

**Comment by Erioldoesdesign** [comment]
@oilsinwater @SaptakS Shall I merge this so I can test?

**Comment by SaptakS** [comment]
I have made the changes that I had requested. So going to approve this and merge. 

@Erioldoesdesign you can also use the details link shown in the row "netlify/subtle-medovik-58f1c6/deploy-preview — Deploy Preview ready! " in the section shown in the below screenshot to test the new changes.
image

**Review by SaptakS — APPROVED** [review]

**Pull request merged**
